### ISSUE TITLE
软件的一些错误

### ISSUE THREAD

**Issue by Yingqidaoge** [FuckAntiAddiction/BiligameAddictionNotLimited#10]
一进软件就报错了不知道该怎么解决
java.io.FileNotFoundException: https://api.github.com/repositories/395314078/releases
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
	at java.net.URL.openStream(URL.java:1058)
	at cn.enaium.banl.MainActivity.onCreate$checkUpdate$lambda-2(MainActivity.kt:70)
	at cn.enaium.banl.MainActivity.lambda$2B-tN_0t1cC0pXrnyVzWhc9LvpU(MainActivity.kt)
	at cn.enaium.banl.-$$Lambda$MainActivity$2B-tN_0t1cC0pXrnyVzWhc9LvpU.run(lambda)
	at java.lang.Thread.run(Thread.java:760)
然后我没管他继续进灵魂潮汐就显示sdk登录失败

**Comment by Yingqidaoge** [comment]
![Screenshot_2021-10-04-22-11-42-717_cn enaium banl](https://user-images.githubusercontent.com/91895856/135866726-fc277b3b-9609-4c6f-b864-c93af15ad5b0.jpg)

**Comment by Hantaisang** [comment]
你代理用192.168.00.00试试

**Comment by Enaium** [comment]
版本检测没有网络权限 把自动检测更新关了就行了

**Comment by Yingqidaoge** [comment]
> 你代理用192.168.00.00试试

这样就启动失败了

**Comment by Yingqidaoge** [comment]
> 你代理用192.168.00.00试试

12:25:06][ERROR]检测失败
[12:25:06][ERROR]java.io.FileNotFoundException: https://api.github.com/repositories/395314078/releases
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
	at java.net.URL.openStream(URL.java:1058)
	at cn.enaium.banl.MainActivity.onCreate$checkUpdate$lambda-2(MainActivity.kt:70)
	at cn.enaium.banl.MainActivity.lambda$2B-tN_0t1cC0pXrnyVzWhc9LvpU(MainActivity.kt)
	at cn.enaium.banl.-$$Lambda$MainActivity$2B-tN_0t1cC0pXrnyVzWhc9LvpU.run(lambda)
	at java.lang.Thread.run(Thread.java:760)
